baseURL: https;//arlabosse.co
title: Arlabosse
paginate: 5
theme: charlolamode



menu:
    main:
        #- name: Biography
         # url: /contact/
          #weight: 30
        - name: Models & Articles
          url: /articles/
          weight: 20
        - name: Projects
          url: /projects/
          weight: 15

     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Casimir Arlabosse


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: false

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Casimir Arlabosse
        description: |

          Hello, my name is Casimir.
        

          I'm currently a student at HKU & MBS.


          Interested in all things finance, tech and stats.


          Affiliated with Arietis & Baucampus.
        imageUrl: "/images/profile.png"
        imageTitle: carlabosse
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Latest Model
              url: /articles/airbnb
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/casiar"
        - name: linkedin
          url: "https://www.linkedin.com/in/arlabossecasimir/"
        - name: cv
          url: "https://arlabosse.co/cv.pdf"
        #- name: researchgate
         # url: "https://www.researchgate.net/profile/casimir-arlabosse"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

